name: Deploy to Static Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout machine-learning repository
      uses: actions/checkout@v2
      with:
        path: machine-learning

    - name: Checkout static repository
      uses: actions/checkout@v2
      with:
        repository: test-jupyter-notebook/static
        token: ${{ secrets.GH_PAT }}
        path: static

    - name: Copy assets to static repository
      run: |
        cp -R machine-learning//open-machine-learning-jupyter-book/assets static/assets

    - name: Commit and push to static repository
      run: |
        cd static
        git config user.name "zyc95"
        git config user.email "zhaoyucheng@live.cn"
        git add .
        git commit -m "Update images from machine-learning repository" || true
        git push


    - name: Checkout demo repository
      uses: actions/checkout@v2
      with:
        repository: test-jupyter-notebook/demo
        token: ${{ secrets.GH_PAT }}
        path: demo

    - name: Copy open-machine-learning-jupyter-book to juypter repository
      run: |
        find machine-learning/open-machine-learning-jupyter-book/assignments -type f -name "*.md" -exec sed -i '' 's|\.\./\{1,\}assets|https://test-jupyter-notebook.github.io/static/assets|g; s|\.\./\{1,\}images|https://test-jupyter-notebook.github.io/static/images|g; s|\.\./||g; s|/|\\/|g' {} \;
        find machine-learning/open-machine-learning-jupyter-book/assignments -type f -name "*.ipynb" -exec sed -i '' 's|\.\./\{1,\}assets|https://test-jupyter-notebook.github.io/static/assets|g; s|\.\./\{1,\}images|https://test-jupyter-notebook.github.io/static/images|g; s|\.\./||g; s|/|\\/|g' {} \;
        find machine-learning/open-machine-learning-jupyter-book/assignments -type f -name "*.md" -exec sed -i '' 's|\.\./\{1,\}assets|https://test-jupyter-notebook.github.io/static/assets|g; s|\.\./\{1,\}assets|https://test-jupyter-notebook.github.io/static/assets|g; s|\.\./||g; s|/|\\/|g' {} \;
        find machine-learning/open-machine-learning-jupyter-book/assignments -type f -name "*.ipynb" -exec sed -i '' 's|\.\./\{1,\}assets|https://test-jupyter-notebook.github.io/static/assets|g; s|\.\./\{1,\}assets|https://test-jupyter-notebook.github.io/static/assets|g; s|\.\./||g; s|/|\\/|g' {} \;

        cp -R machine-learning/open-machine-learning-jupyter-book/assignments demo/assignments

    - name: Commit and push to static repository
      run: |
        cd demo
        git config user.name "zyc95"
        git config user.email "zhaoyucheng@live.cn"
        git add .
        git commit -m "Update images from machine-learning repository" || true
        git push
